// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzAvT_eCUR6IahVMk5N5icSCZMYNOQxeE',
    appId: '1:756867061198:android:036727053a4956b309479f',
    messagingSenderId: '756867061198',
    projectId: 'tiers-22911',
    databaseURL: 'https://tiers-22911-default-rtdb.firebaseio.com',
    storageBucket: 'tiers-22911.appspot.com',
  );
}
